spring:
  application:
    name: sukream
  datasource:
    url: jdbc:oracle:thin:@dblab.dongduk.ac.kr:1521/orclpdb
    username: s250205
    password: 51753
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    format_sql: true

jwt:
  secret: secretKey-authorization-jwt-manage-token

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.security: DEBUG
    feign: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full